add_rules('mode.debug', 'mode.release', 'mode.releasedbg')
add_rules('plugin.compile_commands.autoupdate', { outputdir = '.' })
set_policy('package.install_locally', true)

set_toolchains('msvc')
set_runtimes('MD')

-- add_requires('nous-native nightly')

add_requires('loong-engine', 'nous')
includes('loong')
includes('package')
-- includes('nous-prelude')
-- includes('nous-rs')
-- includes('nous-view')
-- includes('nous-frondend/src-tauri')
includes('sketch-view-app')
includes('sketch-render')
includes('sketch-rs')
includes('sketch-app')
