using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using LoongCAD.Common;
using LoongCAD.Geometry;
using LoongCAD.Util;
using LoongCAD.STC;

namespace UI
{
    public class MainMenu : CustomMenu
    {
        public MainMenu() {
            this.addItems(new ToolStripItem[] {
                group("编辑", new ToolStripItem[] {
                    fu("撤销", "edit_undo"),
                    fu("重做", "edit_redo"),
                    sep(),
                    fu("复制", "edit_copy"),
                    fu("移动", "edit_move"),
                    group("参数复制", new ToolStripItem[] {
                        fu("线性复制...", "edit_copy_line"),
                        fu("旋转复制...", "edit_copy_rotate"),
                        fu("镜像复制...", "edit_copy_mirror"),
                        fu("到另一平面", "edit_copy_by_plane"),
                        fu("到另一物体", "edit_copy_by_obj"),
                        fu("从模型复制", "edit_copy_objs_from_model"),
                    }),
                    group("参数移动", new ToolStripItem[] {
                        fu("线性移动...", "edit_move_line"),
                        fu("旋转移动...", "edit_move_rotate"),
                        fu("镜像移动...", "edit_move_mirror"),
                        fu("到另一平面", "edit_move_by_plane"),
                        fu("到另一物体", "edit_move_by_obj"),
                    }),
                    fu("删除", "edit_del"),
                    sep(),
                    group("选择", new ToolStripItem[] {
                        fu("全选", "edit_pick_all"),
                        fu("回退选择", "sel_cur_objs_undo"),
                        fu("重做选择", "sel_cur_objs_redo"),
                        fu("对象组管理器", "sel_obj_group_mgr"),
                    }),
                    sep(),
                    fu("组合", "edit_combine_part"),
                    group("拆分", new ToolStripItem[] {
                        fu("梁", "edit_split_part"),
                        fu("板", "edit_split_plate"),
                        fu("用零件分割梁", "edit_split_part_by_part"),
                    }),
                    group("切割", new ToolStripItem[] {
                        fu("线对齐", "cut_align_line"),
                        fu("线切割", "cut_line"),
                        fu("面对齐", "cut_align_plane"),
                        fu("面切割", "cut_plane"),
                        fu("3点切割", "cut_3p"),
                        fu("零件切割", "cut_part"),
                        fu("多边形切割", "cut_poly"),
                        fu("梁端斜切", "cut_beams_crossmid"),
                    }),
                    group("延长零件", new ToolStripItem[] {
                        fu("延长到线", "stretch_to_line"),
                        fu("延长到物体", "stretch_to_object"),
                    }),
                    group("焊接准备", new ToolStripItem[] {
                        fu("零件切割准备件", "cut_groove"),
                        fu("多边形切割准备件", "cut_groove_poly"),
                    }),
                    fu("编辑切割目标", "cut_edit_cuttee"),
                    fu("编辑多边形板", "detail_edit_polygon_plate"),
                    sep(),
                    fu("重复最后一步操作", "edit_invoke_recent_call"),
                    sep(),
                    fu("中断", "edit_stop"),
                    sep(),
                    fu("属性", "edit_props"),
                }),

                group("视图", new ToolStripItem[] {
                    group("创建模型视图", new ToolStripItem[] {
                        fu("基本视图", "view_create_model_base"),
                        fu("2点创建", "view_create_model_2p"),
                        fu("3点创建", "view_create_model_3p"),
                        fu("沿工作平面", "view_create_model_by_workplane"),
                        fu("沿轴线", "view_create_model_by_grid"),
                        group("延零件面", new ToolStripItem[] {
                            fu("前面", "view_create_model_by_part_front"),
                            fu("顶面", "view_create_model_by_part_top"),
                            fu("后面", "view_create_model_by_part_back"),
                            fu("底面", "view_create_model_by_part_bottom"),
                        }),
                    }),
                    group("创建零件视图", new ToolStripItem[] {
                        fu("3D视图", "view_create_obj_3d", new object[] { "pick_part", true}),
                        fu("默认视图", "view_create_obj_def", new object[] { "pick_part", true}),
                        fu("无形变视图", "view_create_obj_ortho", new object[] { "pick_part", true}),
                    }),
                    group("创建组件视图", new ToolStripItem[] {
                        fu("3D视图", "view_create_obj_3d", new object[] { "pick_comp", true}),
                        fu("默认视图", "view_create_obj_def", new object[] { "pick_comp", true}),
                        fu("无形变视图", "view_create_obj_ortho", new object[] { "pick_comp", true}),
                    }),
                    fu("视图列表...", "view_list"),
                    sep(),
                    group("表示法", new ToolStripItem[] {
                        group("零件", new ToolStripItem[] {
                            fu("线框", "view_rdmode_wireframe"),
                            fu("半透明", "view_rdmode_trans"),
                            fu("隐藏线", "view_rdmode_hidden_lines"),
                            fu("渲染", "view_rdmode_edgeface"),
                            fu("仅选中", "view_rdmode_sel_only"),
                        }),
                        group("组件", new ToolStripItem[] {
                            fu("线框", "view_rdcompmode_wireframe"),
                            fu("半透明", "view_rdcompmode_trans"),
                            fu("隐藏线", "view_rdcompmode_hidden_lines"),
                            fu("渲染", "view_rdcompmode_edgeface"),
                            fu("仅选中", "view_rdcompmode_sel_only"),
                        }),
                    }),
                    fu("隐藏对象", "view_hide_objs"),
                    sep(),
                    group("设置工作平面", new ToolStripItem[] {
                        fu("世界坐标系...", "view_set_workplane_by_world"),
                        fu("1点创建", "view_set_workplane_1p"),
                        fu("2点创建", "view_set_workplane_2p"),
                        fu("3点创建", "view_set_workplane_3p"),
                        fu("当前视图平面", "view_set_workplane_by_viewplane"),
                        sep(),
                        fu("零件前面", "view_set_workplane_by_part_front"),
                        fu("零件顶面", "view_set_workplane_by_part_top"),
                        fu("零件后面", "view_set_workplane_by_part_back"),
                        fu("零件底面", "view_set_workplane_by_part_bottom"),
                    }),
                    group("设置工作区", new ToolStripItem[] {
                        fu("2点设置", "view_set_focused_box_2p"),
                        sep(),
                        fu("视图全景", "view_set_focused_box_by_view"),
                        fu("模型全景", "view_set_focused_box_by_model"),
                        sep(),
                        fu("选中零件", "view_set_focused_box_by_part"),
                    }),
                    fu("创建裁剪面", "view_create_clip"),
                    fu("切换3D/平面", "view_switch_type"),
                    fu("重置视角", "view_reset_cam"),
                    sep(),
                    group("缩放", new ToolStripItem[] {
                        fu("缩放选中对象", "view_zoom_by_part"),
                        sep(),
                        fu("放大", "view_zoom_in"),
                        fu("缩小", "view_zoom_out"),
                        fu("恢复原始尺寸", "view_zoom_by_workbox"),
                    }),
                    group("移动", new ToolStripItem[] {
                        fu("平移", "view_trans_by_hand"),
                        sep(),
                        fu("向右移动", "view_move_right"),
                        fu("向左移动", "view_move_left"),
                        fu("向下移动", "view_move_down"),
                        fu("向上移动", "view_move_up"),
                        sep(),
                        fu("光标定心", "view_center_by_cursor"),
                    }),
                    group("旋转", new ToolStripItem[] {
                        fu("横向+15", "view_rotate_h15"),
                        fu("横向-15", "view_rotate_hn15"),
                        fu("纵向+15", "view_rotate_v15"),
                        fu("纵向-15", "view_rotate_vn15"),
                        sep(),
                        fu("横向+5", "view_rotate_h5"),
                        fu("横向-5", "view_rotate_hn5"),
                        fu("纵向+5", "view_rotate_v5"),
                        fu("纵向-5", "view_rotate_vn5"),
                        sep(),
                        cfu("禁用旋转", "view_rotate_enable"),
                    }),
                    fu("设置相机轴心并旋转", "view_pick_pivot_rotate"),
                    fu("设置相机轴心", "view_pick_pivot"),
                    fu("漫游", "view_free_walk"),
                    sep(),
                    fu("视图列表...", "view_list"),
                    fu("视图属性...", "view_props"),
                    sep(),
                    fu("重绘", "view_redraw"),
                }),

                group("辅助", new ToolStripItem[] {
                    fu("创建轴网...", "helper_create_grid"),
                    fu("添加轴线", "helper_add_grid_line"),
                    sep(),
                    fu("添加辅助线", "helper_create_line"),
                    group("添加辅助圆", new ToolStripItem[] {
                        fu("圆心+半径", "helper_create_circle_or"),
                        fu("3点", "helper_create_circle_3p"),
                    }),
                    fu("添加辅助平面", "helper_create_quad"),
                    group("添加辅助点", new ToolStripItem[] {
                        fu("在延长线上", "helper_create_pt_ext"),
                        fu("平行于直线", "helper_create_pt_off"),
                        fu("等分线段", "helper_create_pt_div"),
                        fu("工作面点阵列", "helper_create_pt_plane"),
                        fu("直线上投影", "helper_create_pt_proj"),
                        group("沿弧线", new ToolStripItem[] {
                            fu("圆心+半径", "helper_create_pt_arc_or"),
                            fu("3点", "helper_create_pt_arc_3p"),
                        }),
                        fu("线与圆切点", "helper_create_pt_circle_tangent"),
                        group("交点", new ToolStripItem[] {
                            fu("两直线", "helper_create_pt_line_inter"),
                            fu("平面与直线", "helper_create_pt_line_plane_inter"),
                            fu("零件与直线", "helper_create_pt_line_part_inter"),
                            fu("圆与直线", "helper_create_pt_line_circle_inter"),
                            fu("零件轴线", "helper_create_pt_part_inter"),
                        }),
                        fu("任意", "helper_create_pt_free"),
                        sep(),
                        fu("螺栓组", "helper_create_pt_bolt_group"),
                        fu("轴网交点", "helper_create_pt_grid"),
                    }),
                    sep(),
                    fu("轴网属性...", "helper_grid_props"),
                }),

                group("建模", new ToolStripItem[] {
                    group("创建钢构零件", new ToolStripItem[] {
                        fu("柱", "create_sp_col"),
                        fu("梁", "create_sp_beam"),
                        fu("正交梁", "create_sp_beam_ortho"),
                        fu("曲梁", "create_sp_curve_beam"),
                        fu("折形梁", "create_sp_poly_beam"),
                        fu("弯扭梁", "create_sp_twist_beam"),
                        fu("双截面", "create_sp_tween_beam"),
                        fu("板", "create_sp_plate"),
                        fu("梯形板", "create_sp_tzplate"),
                    }),
                    group("钢结构属性", new ToolStripItem[] {
                        fu("柱...", "sp_col_props"),
                        fu("梁...", "sp_beam_props"),
                        fu("正交梁...", "sp_beam_ortho_props"),
                        fu("弯扭梁...", "sp_twist_beam_props"),
                        fu("双截面...", "sp_tween_beam_props"),
                        fu("板...", "sp_plate_props"),
                        fu("梯形板...", "sp_tzplate_props"),
                    }),
                    sep(),
                    group("创建混凝土", new ToolStripItem[] {
                        fu("基础", "create_cp_padfoot"),
                        //fu("条形基础", "create_cp_strip_foot"),
                        fu("柱", "create_cp_col"),
                        fu("梁", "create_cp_beam"),
                        fu("折形梁", "create_cp_strip_beam"),
                        fu("板", "create_cp_slab"),
                        fu("墙", "create_cp_panel"),
                    }),
                    group("混凝土属性", new ToolStripItem[] {
                        fu("基础...", "cp_padfoot_props"),
                        fu("梁...", "cp_beam_props"),
                        fu("柱...", "cp_col_props"),
                        fu("板...", "cp_slab_props"),
                    }),
                    sep(),
                    group("批量布置", new ToolStripItem[] {
                        fu("柱", "create_sp_col_by_grid"),
                        fu("梁", "create_sp_beam_by_grid"),
                        fu("次梁", "create_sp_subbeam_by_grid"),
                        fu("正交梁", "create_sp_beam_ortho_by_grid"),
                        sep(),
                        fu("混凝土基础", "create_cp_padfoot_by_grid"),
                        fu("混凝土柱", "create_cp_col_by_grid"),
                        fu("混凝土梁", "create_cp_beam_by_grid"),
                    }),
                    sep(),
                    group("截面型材", new ToolStripItem[] {
                        fu("截面管理器...", "profile_mgr"),
                        fu("自定义截面...", "profile_custom"),
                    }),
                    fu("材质管理器...", "mtrl_mgr"),
                }),

                group("细部", new ToolStripItem[] {
                    group("螺栓", new ToolStripItem[] {
                        fu("创建螺栓", "detail_create_bolt"),
                        fu("编辑螺栓主次零件", "detail_bolt_edit"),
                        sep(),
                        fu("螺栓配置", "detail_bolt_mgr"),
                    }),
                    group("焊接", new ToolStripItem[] {
                        fu("创建零件间焊接", "detail_create_auto_weld_between_parts"),
                        fu("创建多边形焊接", "detail_create_polygon_weld_between_parts"),
                        fu("单零件焊接", "detail_create_polygon_weld_by_single_part"),
                        fu("编辑焊接", "detail_weld_edit"),
                    }),
                    //sep(),
                    //group("创建钢筋", new ToolStripItem[] {
                    //    fu("钢筋", "detail_create_rfbar_poly"),
                    //    fu("弯曲钢筋", "detail_create_rfbar_curve"),
                    //    fu("环形钢筋", "detail_create_rfbar_circle"),
                    //    sep(),
                    //    fu("钢筋组", "detail_create_rfbar_poly_group"),
                    //    fu("弯曲钢筋组", "detail_create_rfbar_curve_group"),
                    //    fu("环形钢筋组", "detail_create_rfbar_circle_group"),
                    //    sep(),
                    //    fu("钢筋网", "detail_create_rfbar_mesh_group"),
                    //}),
                    //sep(),
                    //group("表面处理", new ToolStripItem[] {
                    //    fu("添加到整个零件", "detail_surf_add_part"),
                    //}),
                    sep(),
                    fu("螺栓属性...", "detail_bolt_props"),
                    fu("焊接属性...", "detail_weld_props"),
                    //group("钢筋属性", new ToolStripItem[] {
                    //    fu("钢筋...", "detail_rfbar_poly_props"),
                    //    sep(),
                    //    fu("钢筋组...", "detail_rfbar_poly_group_props"),
                    //    fu("弯曲钢筋组...", "detail_rfbar_curve_group_props"),
                    //    fu("环形钢筋组...", "detail_rfbar_circle_group_props"),
                    //    sep(),
                    //    fu("钢筋网...", "detail_rfbar_mesh_group_props"),
                    //}),
                }),

                group("构件", new ToolStripItem[] {
                    fu("添加到构件", "assembly_add_sub"),
                    fu("设为构件新主零件", "assembly_set_main"),
                    fu("从构件中删除", "assembly_remove"),
                    fu("组合成构件", "assembly_new"),
                    fu("炸开顶层构件", "assembly_explode_root"),
                    fu("炸开子构件", "assembly_explode_sub"),
                    sep(),
                    fu("添加到砼构件", "cast_unit_add_sub"),
                    fu("设为砼构件新主零件", "cast_unit_set_main"),
                    fu("从砼构件中删除", "cast_unit_remove"),
                    fu("组合成砼构件", "cast_unit_new"),
                    fu("炸开顶层砼构件", "cast_unit_explode_root"),
                    fu("炸开子砼构件", "cast_unit_explode_sub"),
                }),

                group("组件", new ToolStripItem[] {
                    fu("组件管理器...", "comp_explorer"),
                    fu("创建当前组件", "comp_create_cur"),
                    sep(),
                    fu("自定义组件...", "comp_custom"),
                    fu("编辑组件...", "comp_edit"),
                    sep(),
                    fu("炸开组件", "comp_explode"),
                    sep(),
                    fu("组件首选项...", "comp_preference"),
                }),

                group("图纸", new ToolStripItem[] {
                    group("编号", new ToolStripItem[] {
                        fu("编号选中对象", "number_sel_objs"),
                        fu("编号修改过的对象", "number_modified_objs"),
                        fu("全部重新编号", "renumber_all"),
                        fu("编号焊接", "number_weld"),
                        sep(),
                        group("修改", new ToolStripItem[] {
                            fu("零件编号...", "number_modify_part"),
                            fu("构件编号...", "number_modify_ass"),
                            //fu("零件多重编号...", "number_modify_multi_part"),
                            //fu("构件多重编号...", "number_modify_multi_ass"),
                            //fu("系列编号...", "number_modify_family"),
                        }),
                        group("清除", new ToolStripItem[] {
                            fu("零件和构件编号", "number_clear_part_ass"),
                            fu("零件编号", "number_clear_part"),
                            fu("构件编号", "number_clear_ass"),
                            fu("钢筋编号", "number_clear_rfbar"),
                        }),
                        sep(),
                        fu("锁定/解锁...", "number_lock_unlock"),
                        sep(),
                        fu("编号设置...", "number_props"),
                    }),
                    sep(),
                    fu("图纸列表...", "dr_file_draw_list"),
                    sep(),
                    fu("创建图纸", "dr_create_draw"),
                    fu("创建零件图", "dr_create_draw_part"),
                    fu("创建构件图", "dr_create_draw_ass"),
                    fu("创建整体布置图", "dr_create_draw_arrangement"),
                    group("创建多件图", new ToolStripItem[]
                    {
                        fu("零件图", "dr_create_draw_multi_part"),
                        fu("构件图", "dr_create_draw_multi_ass"),
                    }),
                    sep(),
                    fu("模板编辑器", "dr_edit_tmpl_editor"),
                    fu("符号编辑器", "dr_edit_symbol_editor"),
                    sep(),
                    fu("零件图属性", "dr_draw_part_props"),
                    fu("构件图属性", "dr_draw_ass_props"),
                    fu("整体布置图属性", "dr_draw_arrangement_props"),
                    fu("多件图属性", "dr_draw_multiple_props"),
                }),

                group("报告", new ToolStripItem[] {
                    fu("创建报告...", "report_create"),
                    sep(),
                    fu("模板编辑器...", "report_tmpl_editor"),
                }),

                group("D5", new ToolStripItem[] {
                    fu("直线", "create_straightLine"),
                    fu("绘制矩形", "draw_rectangle"),
                    fu("绘制多边形", "draw_polygon"),
                    fu("绘制圆", "draw_circle"),
                    fu("绘制圆弧", "draw_arc"),
                    fu("移动", "common_translate"),
                    fu("旋转", "common_rotate"),
                    fu("缩放", "common_scale"),
                    fu("偏移", "common_buffer"),
                    fu("TRS", "common_trs"),
                    fu("绘制样条曲线", "draw_spline"),
                    fu("编辑控制点", "edit_nurbs"),
                    fu("沿法线挤出", "extrude_polygon"),
                    fu("沿任意方向挤出", "extrude_nurbs"),
                    fu("沿路径挤出", "extrude_path")
                }),

                group("工具", new ToolStripItem[] {
                    group("测量", new ToolStripItem[] {
                        fu("距离", "measure_dist"),
                        fu("水平距离", "measure_dist_h"),
                        fu("竖直距离", "measure_dist_v"),
                        fu("角度", "measure_angl"),
                        fu("弧", "measure_arc"),
                        fu("螺栓间距", "measure_bolt"),
                    }),
                    fu("碰撞检查...", "tool_clash_mgr"),
                    fu("状态管理器...", "tool_phase_mgr"),
                    sep(),
                    fu("颜色等级...", "tool_color_mgr"),
                    fu("模型首选项...", "tool_options"),
                    sep(),
                    fu("快捷键...", "tool_shortcut_mgr"),
                    fu("自定义工具栏...", "tool_cus_bar"),
                    fu("系统配色...", "tool_pallete_mgr"),
                    fu("系统设置...", "tool_settings"),
                    group("偏好", new ToolStripItem[] {
                        cfu("鼠标滑过高亮", "tool_hover_highlight"),
                        cfu("显示捕捉符号", "tool_snap_symbol_vis"),
                        cfu("切割提示色", "tool_cut_color"),
                        cfu("自动碰撞检测", "tool_auto_occ_detect"),
                    }),
                    sep(),
                    group("输入坐标", new ToolStripItem[] {
                        fu("相对", "tool_snap_point_by_input_relative"),
                        fu("绝对", "tool_snap_point_by_input_absolute"),
                        fu("全局", "tool_snap_point_by_input_global"),
                    }),
                    group("切换坐标锁定", new ToolStripItem[] {
                        fu("X轴", "tool_snap_lock_x"),
                        fu("Y轴", "tool_snap_lock_y"),
                        fu("Z轴", "tool_snap_lock_z"),
                    }),
                    sep(),
                    fu("执行脚本...", "tool_run_script"),
#if DEBUG //内部工具，仅在Debug下暴露
                    sep("sep_cvt_tk"),
                    fu("转换TK截面配置...", "tool_convert_tk_profile"),
                    fu("转换TK材质配置...", "tool_convert_tk_mtrl"),
                    fu("转换TK螺栓配置...", "tool_convert_tk_bolt"),
                    fu("测试窗口...", "tool_test_form"),
#endif
                }),

                group("帮助", new ToolStripItem[] {
                    fu("关于...", "help_about"),
                }),
            });
            ;
        }
    }
}
