//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoongCAD.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoongCAD.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap beam_web_square_cut_t1_b1_l1_r1_83x111 {
            get {
                object obj = ResourceManager.GetObject("beam_web_square_cut_t1_b1_l1_r1_83x111", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap bottom_under_board_t1_b1_l1_r1_72x176 {
            get {
                object obj = ResourceManager.GetObject("bottom_under_board_t1_b1_l1_r1_72x176", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap btn_check {
            get {
                object obj = ResourceManager.GetObject("btn_check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_beam_cut_access_hole_t1_b1_l1_r1_72x309 {
            get {
                object obj = ResourceManager.GetObject("cbo_beam_cut_access_hole_t1_b1_l1_r1_72x309", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_beam_cut_bottom_flange_cut_t1_b1_l1_r1_75x130 {
            get {
                object obj = ResourceManager.GetObject("cbo_beam_cut_bottom_flange_cut_t1_b1_l1_r1_75x130", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_beam_cut_end_prepare_t1_b1_l1_r1_60x265 {
            get {
                object obj = ResourceManager.GetObject("cbo_beam_cut_end_prepare_t1_b1_l1_r1_60x265", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_beam_cut_top_flange_cut_t1_b1_l1_r1_75x130 {
            get {
                object obj = ResourceManager.GetObject("cbo_beam_cut_top_flange_cut_t1_b1_l1_r1_75x130", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_beam_end_cut_t1_b1_l1_r1_81x224 {
            get {
                object obj = ResourceManager.GetObject("cbo_beam_end_cut_t1_b1_l1_r1_81x224", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_beam_end_flange_cut_t1_b1_l1_r1_80x111 {
            get {
                object obj = ResourceManager.GetObject("cbo_beam_end_flange_cut_t1_b1_l1_r1_80x111", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_beam_end_web_cut_t1_b1_l1_r1_83x111 {
            get {
                object obj = ResourceManager.GetObject("cbo_beam_end_web_cut_t1_b1_l1_r1_83x111", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_bolt_shape_t1_b1_l1_r1_81x220 {
            get {
                object obj = ResourceManager.GetObject("cbo_bolt_shape_t1_b1_l1_r1_81x220", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_chamfer_types_bottom_left_line_t1_b1_l1_r1_40x439 {
            get {
                object obj = ResourceManager.GetObject("cbo_chamfer_types_bottom_left_line_t1_b1_l1_r1_40x439", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_chamfer_types_bottom_left_none {
            get {
                object obj = ResourceManager.GetObject("cbo_chamfer_types_bottom_left_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_chamfer_types_bottom_right_line_t1_b1_l1_r1_40x439 {
            get {
                object obj = ResourceManager.GetObject("cbo_chamfer_types_bottom_right_line_t1_b1_l1_r1_40x439", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_chamfer_types_bottom_right_none {
            get {
                object obj = ResourceManager.GetObject("cbo_chamfer_types_bottom_right_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_chamfer_types_top_left_line_t1_b1_l1_r1_40x439 {
            get {
                object obj = ResourceManager.GetObject("cbo_chamfer_types_top_left_line_t1_b1_l1_r1_40x439", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_chamfer_types_top_left_none {
            get {
                object obj = ResourceManager.GetObject("cbo_chamfer_types_top_left_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_chamfer_types_top_right_line_t1_b1_l1_r1_40x438 {
            get {
                object obj = ResourceManager.GetObject("cbo_chamfer_types_top_right_line_t1_b1_l1_r1_40x438", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_chamfer_types_top_right_none {
            get {
                object obj = ResourceManager.GetObject("cbo_chamfer_types_top_right_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_concave_chamfer_types_bottom_left_line {
            get {
                object obj = ResourceManager.GetObject("cbo_concave_chamfer_types_bottom_left_line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_concave_chamfer_types_bottom_left_round {
            get {
                object obj = ResourceManager.GetObject("cbo_concave_chamfer_types_bottom_left_round", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_concave_chamfer_types_bottom_right_line {
            get {
                object obj = ResourceManager.GetObject("cbo_concave_chamfer_types_bottom_right_line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_concave_chamfer_types_bottom_right_round {
            get {
                object obj = ResourceManager.GetObject("cbo_concave_chamfer_types_bottom_right_round", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_concave_chamfer_types_top_left_line {
            get {
                object obj = ResourceManager.GetObject("cbo_concave_chamfer_types_top_left_line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_concave_chamfer_types_top_left_round {
            get {
                object obj = ResourceManager.GetObject("cbo_concave_chamfer_types_top_left_round", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_concave_chamfer_types_top_right_line {
            get {
                object obj = ResourceManager.GetObject("cbo_concave_chamfer_types_top_right_line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_concave_chamfer_types_top_right_round {
            get {
                object obj = ResourceManager.GetObject("cbo_concave_chamfer_types_top_right_round", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_convex_shear_orientation_t1_b1_l1_r1_87x146 {
            get {
                object obj = ResourceManager.GetObject("cbo_convex_shear_orientation_t1_b1_l1_r1_87x146", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_double_plate_creation_t1_b1_l1_r1_132x447 {
            get {
                object obj = ResourceManager.GetObject("cbo_double_plate_creation_t1_b1_l1_r1_132x447", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_double_plate_shape_t1_b1_l1_r1_132x266 {
            get {
                object obj = ResourceManager.GetObject("cbo_double_plate_shape_t1_b1_l1_r1_132x266", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_haunch_creation_t1_b1_l1_r1_171x404 {
            get {
                object obj = ResourceManager.GetObject("cbo_haunch_creation_t1_b1_l1_r1_171x404", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_multi_stiff_creation_t1_b1_l1_r1_95x321 {
            get {
                object obj = ResourceManager.GetObject("cbo_multi_stiff_creation_t1_b1_l1_r1_95x321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_multi_stiff_orientation_t1_b1_l1_r1_105x277 {
            get {
                object obj = ResourceManager.GetObject("cbo_multi_stiff_orientation_t1_b1_l1_r1_105x277", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_multi_stiff_shape_t1_b1_l1_r1_95x324 {
            get {
                object obj = ResourceManager.GetObject("cbo_multi_stiff_shape_t1_b1_l1_r1_95x324", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_notch_chamfer_t1_b1_l1_r1_91x144 {
            get {
                object obj = ResourceManager.GetObject("cbo_notch_chamfer_t1_b1_l1_r1_91x144", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_notch_flange_cut_shape_t1_b1_l1_r1_95x113 {
            get {
                object obj = ResourceManager.GetObject("cbo_notch_flange_cut_shape_t1_b1_l1_r1_95x113", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_notch_manual_depth_mode_t1_b1_l1_r1_81x149 {
            get {
                object obj = ResourceManager.GetObject("cbo_notch_manual_depth_mode_t1_b1_l1_r1_81x149", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_notch_manual_shape_t1_b1_l1_r1_81x256 {
            get {
                object obj = ResourceManager.GetObject("cbo_notch_manual_shape_t1_b1_l1_r1_81x256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_notch_manual_side_t1_b1_l1_r1_77x182 {
            get {
                object obj = ResourceManager.GetObject("cbo_notch_manual_side_t1_b1_l1_r1_77x182", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_notch_position_t1_b1_l1_r1_81x105 {
            get {
                object obj = ResourceManager.GetObject("cbo_notch_position_t1_b1_l1_r1_81x105", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_notch_shape_t1_b1_l1_r1_82x182 {
            get {
                object obj = ResourceManager.GetObject("cbo_notch_shape_t1_b1_l1_r1_82x182", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_notch_size_mode_t1_b1_l1_r1_91x108 {
            get {
                object obj = ResourceManager.GetObject("cbo_notch_size_mode_t1_b1_l1_r1_91x108", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_notch_size_rounding_t1_b1_l1_r1_91x108 {
            get {
                object obj = ResourceManager.GetObject("cbo_notch_size_rounding_t1_b1_l1_r1_91x108", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_shear_away_side_t1_b1_l1_r1_135x399 {
            get {
                object obj = ResourceManager.GetObject("cbo_shear_away_side_t1_b1_l1_r1_135x399", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_shear_bolt_orientation_t1_b1_l1_r1_76x185 {
            get {
                object obj = ResourceManager.GetObject("cbo_shear_bolt_orientation_t1_b1_l1_r1_76x185", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_shear_end_cut_t1_b1_l1_r1_77x125 {
            get {
                object obj = ResourceManager.GetObject("cbo_shear_end_cut_t1_b1_l1_r1_77x125", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_shear_orientation_t1_b1_l1_r1_76x187 {
            get {
                object obj = ResourceManager.GetObject("cbo_shear_orientation_t1_b1_l1_r1_76x187", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_single_stiff_creation_t1_b1_l1_r1_73x487 {
            get {
                object obj = ResourceManager.GetObject("cbo_single_stiff_creation_t1_b1_l1_r1_73x487", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_single_stiff_orientation_t1_b1_l1_r1_77x125 {
            get {
                object obj = ResourceManager.GetObject("cbo_single_stiff_orientation_t1_b1_l1_r1_77x125", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_weld_contour {
            get {
                object obj = ResourceManager.GetObject("cbo_weld_contour", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_weld_edge_around {
            get {
                object obj = ResourceManager.GetObject("cbo_weld_edge_around", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_weld_finish {
            get {
                object obj = ResourceManager.GetObject("cbo_weld_finish", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cbo_weld_type {
            get {
                object obj = ResourceManager.GetObject("cbo_weld_type", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap center_stiff_rib_pos {
            get {
                object obj = ResourceManager.GetObject("center_stiff_rib_pos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap center_stiff_rib_pos_t1_b1_l1_r1_69x231 {
            get {
                object obj = ResourceManager.GetObject("center_stiff_rib_pos_t1_b1_l1_r1_69x231", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap comp_beam_backbar_over_dist {
            get {
                object obj = ResourceManager.GetObject("comp_beam_backbar_over_dist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap comp_bolt_others {
            get {
                object obj = ResourceManager.GetObject("comp_bolt_others", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap comp_both_others_size {
            get {
                object obj = ResourceManager.GetObject("comp_both_others_size", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap comp_detail_pos_side_profile_view {
            get {
                object obj = ResourceManager.GetObject("comp_detail_pos_side_profile_view", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap comp_detail_pos_side_top_view {
            get {
                object obj = ResourceManager.GetObject("comp_detail_pos_side_top_view", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap hole_size {
            get {
                object obj = ResourceManager.GetObject("hole_size", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap input_lookup {
            get {
                object obj = ResourceManager.GetObject("input_lookup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap input_lookup_clear {
            get {
                object obj = ResourceManager.GetObject("input_lookup_clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap notch_corner_line_t1_b1_l1_r1_91x144 {
            get {
                object obj = ResourceManager.GetObject("notch_corner_line_t1_b1_l1_r1_91x144", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap notch_manual_size_tips_t1_b1_l1_r1_124x117 {
            get {
                object obj = ResourceManager.GetObject("notch_manual_size_tips_t1_b1_l1_r1_124x117", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap notch_rounding_horz_tips {
            get {
                object obj = ResourceManager.GetObject("notch_rounding_horz_tips", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap notch_rounding_vert_tips {
            get {
                object obj = ResourceManager.GetObject("notch_rounding_vert_tips", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap notch_size_horz_tips {
            get {
                object obj = ResourceManager.GetObject("notch_size_horz_tips", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap notch_size_vert_tips {
            get {
                object obj = ResourceManager.GetObject("notch_size_vert_tips", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap perpend_sub_cut_flange_t1_b1_l1_r1_95x113 {
            get {
                object obj = ResourceManager.GetObject("perpend_sub_cut_flange_t1_b1_l1_r1_95x113", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap shear_plane_direction_square_t1_b1_l1_r1_87x146 {
            get {
                object obj = ResourceManager.GetObject("shear_plane_direction_square_t1_b1_l1_r1_87x146", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap side_stiff_rib_pos_t1_b1_l1_r1_64x218 {
            get {
                object obj = ResourceManager.GetObject("side_stiff_rib_pos_t1_b1_l1_r1_64x218", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Snipaste_2023_02_21_16_14_23_t1_b1_l1_r1_112x159 {
            get {
                object obj = ResourceManager.GetObject("Snipaste_2023_02_21_16_14_23_t1_b1_l1_r1_112x159", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap steel_angle_stiff_rib_shape_t1_b1_l1_r1_68x189 {
            get {
                object obj = ResourceManager.GetObject("steel_angle_stiff_rib_shape_t1_b1_l1_r1_68x189", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap sub_part_cut_t1_b1_l1_r1_107x177 {
            get {
                object obj = ResourceManager.GetObject("sub_part_cut_t1_b1_l1_r1_107x177", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap support_angle_direction_type_t1_b1_l1_r1_68x289 {
            get {
                object obj = ResourceManager.GetObject("support_angle_direction_type_t1_b1_l1_r1_68x289", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap support_steel_angle_pos_t1_b1_l1_r1_89x480 {
            get {
                object obj = ResourceManager.GetObject("support_steel_angle_pos_t1_b1_l1_r1_89x480", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap support_steel_angle_rotate_t1_b1_l1_r1_69x140 {
            get {
                object obj = ResourceManager.GetObject("support_steel_angle_rotate_t1_b1_l1_r1_69x140", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap top_support_steel_angle_attach_type_t1_b1_l1_r1_156x420 {
            get {
                object obj = ResourceManager.GetObject("top_support_steel_angle_attach_type_t1_b1_l1_r1_156x420", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap top_under_board_type_t1_b1_l1_r1_72x173 {
            get {
                object obj = ResourceManager.GetObject("top_under_board_type_t1_b1_l1_r1_72x173", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap under_beam_flange_cut_flange_t1_b1_l1_r1_92x131 {
            get {
                object obj = ResourceManager.GetObject("under_beam_flange_cut_flange_t1_b1_l1_r1_92x131", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap under_beam_flange_cut_notch__t1_b1_l1_r1_92x131 {
            get {
                object obj = ResourceManager.GetObject("under_beam_flange_cut_notch__t1_b1_l1_r1_92x131", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap under_board_length_t1_b1_l1_r1_82x107 {
            get {
                object obj = ResourceManager.GetObject("under_board_length_t1_b1_l1_r1_82x107", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
